# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO_Items', '0001_initial'),
        ('User_Login_Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('details', models.CharField(max_length=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO_Items.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Login_Register.UserDetail')),
            ],
        ),
    ]
