# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
