# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO_Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGODetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=10)),
                ('fund', models.IntegerField(default=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO_Items.Item')),
            ],
        ),
    ]
