# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO_Login_Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ngodetails',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO_Login_Register.NGO'),
        ),
    ]
