# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO_Login_Register', '0002_auto_20180317_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngodetails',
            name='fund',
        ),
        migrations.AddField(
            model_name='ngo',
            name='fund',
            field=models.IntegerField(default=1000),
        ),
    ]
